### ISSUE TITLE
All partner’s links open BCD webpage

### ISSUE THREAD

**Issue by BCDMU** [LiamOSullivan/CorkDashboardRepo#10]
All partner’s links open BCD webpage (Maynooth University, SFI, NCG, Cork City Council, Cork County Council, CSO, AIRO, OSI)

**Comment by LiamOSullivan** [comment]
dbFooter to be changed, this is a placeholder image

**Comment by LiamOSullivan** [comment]
These now link to external partner pages. Responsive layout applied.
