### ISSUE TITLE
Sidebar Scaling

### ISSUE THREAD

**Issue by BCDMU** [LiamOSullivan/CorkDashboardRepo#2]
When making the browser window smaller, the sidebar does not scale properly, causing the text to encroach on the main content.

Windows 10 Desktop, Internet Explorer. 

-LOS

**Comment by LiamOSullivan** [comment]
Original Issue fixed. Now e.g. menu font is too small when viewed on mobile.

**Comment by LiamOSullivan** [comment]
Fixed with breakpoints
