### ISSUE TITLE
Latest News links

### ISSUE THREAD

**Issue by BCDMU** [LiamOSullivan/CorkDashboardRepo#9]
Latest News links:
i.	When clicking at reports link, the new window is divided in two sections. Sidebar not scaled properly. 
ii.	Cork Economic Bulletin Q1 Link – missing webpage
iii.	Real time Link – new page is doubled, overlaid and not scaled. Also, the link is still DublinRealTime (http://corkdashboard.ie/pages/DublinRealtime

**Comment by LiamOSullivan** [comment]
Fixed
